# Initial setup: Run the command `docker compose run --rm fitbit-fetch-data` and enter a valie fitbit refresh token
# make sure the mapped logs and tokens folders exists and owned by 1000 uid, otherwise you may get permission denied error. 
# Check for successful API calls and then exit out with ctrl + c
# Then run docker compose up -d to launch the full stack
# This compose file creates an open read/write access influxdb database with no authentication. You may enable authentication and grant appropriate read/write access to the `fitbit_user` on the `FitbitHealthStats` database manually if you want with additional `INFLUXDB_ADMIN_ENABLED`, `INFLUXDB_ADMIN_USER`, and `INFLUXDB_ADMIN_PASSWORD` ENV variables following influxdb 1.8 guidelines. 
services:
  fitbit-fetch-data:
    restart: unless-stopped
    image: thisisarpanghosh/fitbit-fetch-data:latest
    container_name: fitbit-fetch-data
    volumes:
      - ./logs:/app/logs # logs folder should exist and owned by user id 1500 for influxdb v1.11
      - ./tokens:/app/tokens # tokens folder should esist and owned by user id 1500 for influxdb v1.11
      - /etc/timezone:/etc/timezone:ro
    environment:
      - FITBIT_LOG_FILE_PATH=/app/logs/fitbit.log
      - TOKEN_FILE_PATH=/app/tokens/fitbit.token
      - AUTO_DATE_RANGE=True # Switch between regular update and bulk update mode, read Historical Data Update section in README
      - INFLUXDB_VERSION=1 # supports 1 or 2 or 3
      - INFLUXDB_HOST=influxdb # for influxdb 1.x and 3.x
      - INFLUXDB_PORT=8086 # for influxdb 1.x and 3.x
      # Variables for influxdb 3.x ( additionally you need to change the influxdb container image to 3.x below )
      # - INFLUXDB_V3_ACCESS_TOKEN=your_influxdb_admin_access_token # Required for influxdb V3 (ignored for V1 and V2), Set this to your admin access token (or a token that has database R/W access) - Check README installation notes under point 3 to generate this. 
      # Variables for influxdb 2.x ( additionally you need to change the influxdb container image to 2.x below )
      # - INFLUXDB_BUCKET=your_bucket_name_here # for influxdb 2.x
      # - INFLUXDB_ORG=your_org_here # for influxdb 2.x
      # - INFLUXDB_TOKEN=your_token_here # for influxdb 2.x
      # - INFLUXDB_URL=your_influxdb_server_location_with_port_here # for influxdb 2.x
      # Variables for influxdb 1.x
      - INFLUXDB_USERNAME=fitbit_user # for influxdb 1.x
      - INFLUXDB_PASSWORD=fitbit_password # for influxdb 1.x
      - INFLUXDB_DATABASE=FitbitHealthStats # for influxdb 1.x
      # MAKE SURE you set the application type to PERSONAL. Otherwise, you won't have access to intraday data series, resulting in 40X errors.
      - CLIENT_ID=your_application_client_ID # Change this to your client ID
      - CLIENT_SECRET=your_application_client_secret # Change this to your client Secret
      - DEVICENAME=Your_Device_Name # e.g. "Charge5"
      - LOCAL_TIMEZONE=Automatic # set to "Automatic" for Automatic setup from User profile (if not mentioned here specifically). 
    depends_on:
      - influxdb             

  # We are using influxdb 1.8 in this stack (tested and optimized - better dashboard support)
  influxdb:
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    environment:
      - INFLUXDB_DB=FitbitHealthStats
      - INFLUXDB_USER=fitbit_user
      - INFLUXDB_USER_PASSWORD=fitbit_password
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
      ###############################################################################
      # The following ENV variables are applicable for InfluxDB V3 - No effect for V1
      ###############################################################################
      # - INFLUXDB3_MAX_HTTP_REQUEST_SIZE=10485760
      # - INFLUXDB3_NODE_IDENTIFIER_PREFIX=Influxdb-node1
      # - INFLUXDB3_BUCKET=GarminStats
      # - INFLUXDB3_OBJECT_STORE=file
      # - INFLUXDB3_DB_DIR=/data
      # - INFLUXDB3_QUERY_FILE_LIMIT=5000 # this set to be a very high value if you want to view long term data
    ports:
      - '8086:8086' # Influxdb V3 should map as "8181:8181" (Change INFLUXDB_PORT to 8181 on garmin-fetch-data appropriately for InfluxDB V3)
    volumes:
      - ./influxdb:/var/lib/influxdb # InfluxDB V3 bind mount should be set like - ./influxdb:/data if you set INFLUXDB3_DB_DIR=/data (instead of /var/lib/influxdb) - must be owned by 1500:1500 for influxdb v1.11
    image: 'influxdb:1.11' # You must change this to 'quay.io/influxdb/influxdb3-core:latest' for influxdb V3

  grafana:
    restart: unless-stopped
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_PREINSTALL=marcusolsson-hourly-heatmap-panel
    volumes:
      - './grafana:/var/lib/grafana' # Must be owned by 472:472
    ports:
      - '3000:3000'
    image: 'grafana/grafana:latest'
