{
 "title": "Fitbit Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "TimeZone",
    "label": "Time Zone",
    "query": "America/Toronto, Asia/Kolkata, Europe/Budapest"
   },
   {
    "name": "ActivityGPS",
    "label": "Activity with GPS",
    "query": {
     "query": "SHOW TAG VALUES FROM \"GPS\" WITH KEY = \"ActivityID\" WHERE $timeFilter"
    }
   }
  ]
 },
 "panels": [
  { "title": "Recent Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Support Me!",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<center><a href='https://ko-fi.com/A0A84F3DP' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=6' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a></center>  "
   }
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sync ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HeartRate_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Battery Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Battery remaining",
     "measurement": "DeviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intraday Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Intraday Steps",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Steps_Intraday",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate Distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Heart rate histogram",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"value\") as mean_value FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value <= 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 96",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"value\") as mean_value FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram < 60",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"value\") as mean_value FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 110",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"value\") as mean_value FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 110",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RHR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "RestingHR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Spo2 Today",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SpO2 Intraday",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPO2_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Steps",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Steps_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sleep levels",
     "measurement": "Sleep Levels",
     "query": "SELECT sleep_type FROM sleep_levels WHERE short = false",
     "select": [
      [
       { "params": [ "level" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "isMainSleep", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "SPO2",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 29 },
   "targets": [
    {
     "alias": "Sleep levels",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Sleep Levels",
     "query": "SELECT sleep_type FROM sleep_levels WHERE short = false",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "isMainSleep", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Last Day Total Sleep",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Asleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "select": [
      [
       { "params": [ "minutesAsleep" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  { "title": "Sleep Data - Long Term", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Sleep",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesDeep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesLight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesREM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesAwake" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Efficiency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Efficiency",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Relative Skin Temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Relative Skin Temp ",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Skin Temperature Variation",
     "select": [
      [
       { "params": [ "RelativeValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesDeep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesLight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesREM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesAwake" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "alias": "Sleep Regularity",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Sleep Levels",
     "query": "SELECT median(\"level\") FROM \"Sleep Levels\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  { "title": "Other Long Term Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Resting HR",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RestingHR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HRV",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "DailyRmssd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV",
     "select": [
      [
       { "params": [ "dailyRmssd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spo2 ( Avg )",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPO2",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Breathing Rate",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Breathing Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hourly walk heatmap",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Steps_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "measurement": "Total Steps",
     "query": "SELECT sum(\"value\") FROM \"Steps\" WHERE $timeFilter GROUP BY time(1d, ) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 81 },
   "targets": [
    {
     "alias": "Fat Burn (AZM)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Fat Burn" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Cardio (AZM)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Cardio" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Peak (AZM)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Peak" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesSedentary" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Zones",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 81 },
   "targets": [
    {
     "alias": "Fat Burn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Fat Burn" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Cardio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Cardio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Peak" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "alias": "Weight in KG",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weight",
     "query": "SELECT mean(\"value\")*0.453592 FROM \"weight\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('$TimeZone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "BMI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "BMI",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weight",
     "query": "SELECT mean(\"value\") FROM \"bmi\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('$TimeZone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Avg Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Light Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesLightlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesVeryActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesFairlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesSedentary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 91 },
   "targets": [
    {
     "alias": "Total Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "distance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Calories",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 91 },
   "targets": [
    {
     "alias": "Total Calories",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "calories",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "SELECT mean(value) FROM \"heartrate\" WHERE $timeFilter GROUP BY time(2m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "measurement": "Activity Records",
     "query": "SELECT \"ActivityName\", \"duration\", \"calories\", \"AverageHeartRate\", \"distance\", \"steps\" FROM \"Activity Records\" WHERE $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 105 },
   "targets": [
    {
     "query": "SELECT \"lat\",\"lon\",\"speed_kph\",\"heart_rate\", \"altitude\", \"distance\"\nFROM \"GPS\" \nWHERE \"ActivityID\"::tag = '$ActivityGPS' AND \"distance\"::field > 0\nAND $timeFilter"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "query": "SELECT \"heart_rate\"\nFROM \"GPS\" \nWHERE \"ActivityID\"::tag = '$ActivityGPS' AND \"distance\"::field > 0\nAND $timeFilter"
    }
   ]
  },
  {
   "title": "Distance Vs HR",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "query": "SELECT \"speed_kph\",\"heart_rate\", \"distance\"\nFROM \"GPS\" \nWHERE \"ActivityID\"::tag = '$ActivityGPS' AND \"distance\"::field > 0\nAND $timeFilter"
    }
   ]
  },
  {
   "title": "HR Vs Pace",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "query": "SELECT \"speed_kph\",\"heart_rate\", \"distance\"\nFROM \"GPS\" \nWHERE \"ActivityID\"::tag = '$ActivityGPS' AND \"distance\"::field > 0\nAND $timeFilter"
    }
   ]
  },
  {
   "title": "Pace",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "query": "SELECT \"speed_kph\"\nFROM \"GPS\" \nWHERE \"ActivityID\"::tag = '$ActivityGPS' AND \"distance\"::field > 0\nAND $timeFilter"
    }
   ]
  },
  {
   "title": "Last Charge",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceBatteryLevel",
     "query": "SELECT time FROM \"DeviceBatteryLevel\" WHERE DERIVATIVE(\"value\", 1s) > 0\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Battery Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}